# Generated by Django 6.0 on 2026-01-04 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siniestros', '0003_estudiante_remove_poliza_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='facturacion/documentos/')),
                ('codigo_documento', models.CharField(max_length=100, unique=True, verbose_name='Código de Documento')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_facturacion', to='siniestros.poliza')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido Por')),
            ],
            options={
                'verbose_name': 'Documento de Facturación',
                'verbose_name_plural': 'Documentos de Facturación',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
