# Generated by Django 6.0 on 2026-01-15 08:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('codigo_estudiante', models.CharField(max_length=20, unique=True, verbose_name='Código de Estudiante')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('fallecido', 'Fallecido'), ('egresado', 'Egresado'), ('suspendido', 'Suspendido'), ('graduado', 'Graduado'), ('retirado', 'Retirado')], default='activo', max_length=20)),
                ('tipo_estudio', models.CharField(choices=[('presencial', 'Presencial'), ('distancia', 'Distancia')], max_length=20)),
                ('fecha_defuncion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('carrera', models.CharField(max_length=150, verbose_name='Carrera')),
                ('nivel', models.CharField(blank=True, max_length=50, verbose_name='Nivel/Semestre')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='TcasDocumentos',
            fields=[
                ('doc_cod_doc', models.AutoField(primary_key=True, serialize=False)),
                ('doc_descripcion', models.TextField()),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('doc_size', models.PositiveIntegerField(blank=True, null=True)),
                ('fec_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_edit', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(help_text='Identificador único de la póliza', max_length=50, unique=True, verbose_name='Número de Póliza')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('inactiva', 'Inactiva'), ('suspendida', 'Suspendida')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('monto_cobertura', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('tipo_cobertura', models.CharField(choices=[('basica', 'Cobertura Básica'), ('ampliada', 'Cobertura Ampliada'), ('completa', 'Cobertura Completa')], default='basica', max_length=20, verbose_name='Tipo de Cobertura')),
                ('fecha_inicio', models.DateField(help_text='Fecha en que la póliza entra en vigencia', verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha en que la póliza expira', verbose_name='Fecha de Fin')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('prima_neta', models.DecimalField(decimal_places=2, help_text='Valor mensual de la prima', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Prima Neta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poliza', to='core.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Póliza',
                'verbose_name_plural': 'Pólizas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('asesor', 'Asesor'), ('solicitante', 'Solicitante')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('not_id', models.AutoField(primary_key=True, serialize=False)),
                ('not_fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('not_fecha_proceso', models.DateTimeField(blank=True, null=True)),
                ('not_mensaje', models.TextField(blank=True, null=True)),
                ('not_read', models.BooleanField(blank=True, default=False, null=True)),
                ('not_estado', models.BooleanField(blank=True, default=False, null=True)),
                ('not_celery_task_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('not_poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.poliza')),
                ('not_codcli', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('accidente', 'Accidente'), ('enfermedad', 'Enfermedad grave'), ('hospitalizacion', 'Hospitalización'), ('fallecimiento', 'Fallecimiento'), ('otro', 'Otro')], max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('fecha_evento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre_beneficiario', models.CharField(blank=True, max_length=150)),
                ('relacion_beneficiario', models.CharField(blank=True, max_length=50)),
                ('parentesco', models.CharField(blank=True, max_length=50)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('documento', models.FileField(blank=True, null=True, upload_to='siniestros/')),
                ('comentarios', models.TextField(blank=True)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='core.poliza')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siniestros_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('en_proceso', 'En Proceso')], default='pendiente', max_length=20)),
                ('tipo_poliza', models.CharField(max_length=100)),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.TextField()),
                ('documento_identidad', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asesor_notificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='core.estudiante')),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['numero_poliza'], name='core_poliza_numero__321068_idx'),
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['estado'], name='core_poliza_estado_f89e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['estudiante', 'estado'], name='core_poliza_estudia_99af90_idx'),
        ),
    ]
