# Generated by Django 6.0 on 2026-01-06 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(help_text='Identificador único de la póliza', max_length=50, unique=True, verbose_name='Número de Póliza')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('tipo_cobertura', models.CharField(choices=[('basica', 'Cobertura Básica'), ('ampliada', 'Cobertura Ampliada'), ('completa', 'Cobertura Completa')], default='basica', max_length=20, verbose_name='Tipo de Cobertura')),
                ('fecha_inicio', models.DateField(help_text='Fecha en que la póliza entra en vigencia', verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(help_text='Fecha en que la póliza expira', verbose_name='Fecha de Fin')),
                ('prima_neta', models.DecimalField(decimal_places=2, help_text='Valor mensual de la prima', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Prima Neta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Póliza',
                'verbose_name_plural': 'Pólizas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['numero_poliza'], name='core_poliza_numero__321068_idx'), models.Index(fields=['estado'], name='core_poliza_estado_f89e9d_idx')],
            },
        ),
    ]
