# Generated by Django 6.0 on 2026-01-15 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id_aseguradora', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tcasdocumentos',
            name='estado',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='aseguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='core.aseguradora'),
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id_beneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='core.profile')),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='core.siniestro')),
            ],
        ),
        migrations.AddField(
            model_name='tcasdocumentos',
            name='beneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.beneficiario'),
        ),
        migrations.CreateModel(
            name='DocumentosAseguradora',
            fields=[
                ('id_doc_req', models.AutoField(primary_key=True, serialize=False)),
                ('siniestro_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_documento', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('obligatorio', models.BooleanField(default=True)),
                ('fecha_version', models.DateField(auto_now_add=True)),
                ('aseguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_requeridos', to='core.aseguradora')),
            ],
        ),
    ]
