# Generated by Django 6.0 on 2026-01-07 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('fallecido', 'Fallecido')], default='activo', max_length=20)),
                ('tipo_estudio', models.CharField(choices=[('presencial', 'Presencial'), ('distancia', 'Distancia')], max_length=20)),
                ('fecha_defuncion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='poliza',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='core.estudiante', verbose_name='Estudiante'),
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['estudiante', 'estado'], name='core_poliza_estudia_99af90_idx'),
        ),
    ]
