# Generated by Django 6.0 on 2026-01-08 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estudiante_poliza_estudiante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('not_id', models.AutoField(primary_key=True, serialize=False)),
                ('not_fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('not_fecha_proceso', models.DateTimeField(blank=True, null=True)),
                ('not_mensaje', models.TextField(blank=True, null=True)),
                ('not_read', models.BooleanField(blank=True, default=False, null=True)),
                ('not_celery_task_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('not_codcli', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.profile')),
                ('not_poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.poliza')),
            ],
        ),
    ]
