# Generated by Django 6.0 on 2026-01-15 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aseguradora_tcasdocumentos_estado_poliza_aseguradora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='core.profile'),
        ),
    ]
