# Generated by Django 6.0 on 2026-01-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='fecha_fin',
            field=models.DateTimeField(help_text='Fecha en que la póliza expira', verbose_name='Fecha de Fin'),
        ),
    ]
