# Generated by Django 6.0 on 2026-01-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_solicitud_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('asesor', 'Asesor'), ('solicitante', 'Solicitante'), ('beneficiario', 'Beneficiario'), ('administrador', 'Administrador')], max_length=20),
        ),
    ]
