# Generated by Django 6.0 on 2026-01-18 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosaseguradora',
            name='dias_max_entrega',
            field=models.IntegerField(default=5, help_text='Días máximos para entregar el documento'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='fecha_limite_reporte',
            field=models.DateField(blank=True, help_text='Fecha límite para enviar a aseguradora', null=True),
        ),
        migrations.CreateModel(
            name='ConfiguracionSiniestro',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('dias_max_reporte', models.IntegerField(default=3, help_text='Días máximos para enviar reporte a aseguradora')),
                ('dias_max_documentacion', models.IntegerField(default=7, help_text='Días máximos para completar documentación')),
                ('tipo_siniestro', models.CharField(blank=True, choices=[('accidente', 'Accidente'), ('enfermedad', 'Enfermedad grave'), ('hospitalizacion', 'Hospitalización'), ('fallecimiento', 'Fallecimiento'), ('otro', 'Otro')], max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aseguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_siniestros', to='core.aseguradora')),
            ],
            options={
                'verbose_name': 'Configuración de Siniestro',
                'verbose_name_plural': 'Configuraciones de Siniestros',
            },
        ),
        migrations.CreateModel(
            name='ReglasPoliza',
            fields=[
                ('id_regla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_regla', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dias_vigencia', models.IntegerField(help_text='Días de vigencia de la póliza')),
                ('dias_gracia', models.IntegerField(default=30, help_text='Días de gracia antes del vencimiento')),
                ('max_estudiantes', models.IntegerField(blank=True, help_text='Máximo de estudiantes por póliza', null=True)),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('permite_renovacion', models.BooleanField(default=True)),
                ('requiere_aprobacion', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_polizas', to='core.aseguradora')),
            ],
            options={
                'verbose_name': 'Regla de Póliza',
                'verbose_name_plural': 'Reglas de Pólizas',
            },
        ),
    ]
