# Generated by Django 6.0 on 2026-01-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_poliza_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='not_estado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
