# Generated by Django 6.0 on 2026-01-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_documentosaseguradora_dias_max_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosaseguradora',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
