# Generated by Django 6.0 on 2026-01-14 20:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='TcasProcesos',
            fields=[
                ('pro_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('pro_descripcion', models.TextField()),
                ('pro_nombre', models.CharField(max_length=200)),
                ('pro_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pro_estado', models.CharField(choices=[('parcial', 'Parcial'), ('completo', 'Completo'), ('pendiente', 'Pendiente')], default='pendiente', max_length=50)),
                ('pro_resultado', models.CharField(blank=True, max_length=200, null=True)),
                ('pro_lugar', models.CharField(blank=True, max_length=200, null=True)),
                ('pro_fecha_ini', models.DateField()),
                ('pro_fecha_fin', models.DateField(blank=True, null=True)),
                ('pro_pagado', models.BooleanField(blank=True, default=False, null=True)),
                ('pro_facturado', models.BooleanField(blank=True, default=False, null=True)),
                ('pro_proceso_anterior', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TcasDocumentos',
            fields=[
                ('doc_cod_doc', models.AutoField(primary_key=True, serialize=False)),
                ('doc_descripcion', models.TextField()),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('doc_size', models.PositiveIntegerField(blank=True, null=True)),
                ('fec_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_edit', models.DateTimeField(blank=True, null=True)),
                ('doc_cod_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.tcasprocesos')),
            ],
        ),
        migrations.CreateModel(
            name='TcasActividades',
            fields=[
                ('act_codact', models.AutoField(primary_key=True, serialize=False)),
                ('act_nombre', models.CharField(max_length=200)),
                ('act_estado', models.CharField(choices=[('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], max_length=50)),
                ('act_fecha_ini', models.DateField()),
                ('act_fecha_fin', models.DateField(default=datetime.date.today)),
                ('act_descripcion', models.TextField(blank=True, null=True)),
                ('act_lugar', models.CharField(max_length=200)),
                ('act_tipo', models.CharField(max_length=50)),
                ('act_cod_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='core.tcasprocesos')),
            ],
        ),
    ]
