# Generated by Django 6.0 on 2026-01-18 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_documentosaseguradora_activo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='poliza',
            name='core_poliza_estudia_99af90_idx',
        ),
        migrations.AddField(
            model_name='poliza',
            name='estudiantes',
            field=models.ManyToManyField(related_name='polizas', to='core.estudiante', verbose_name='Estudiantes'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='regla_poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas', to='core.reglaspoliza'),
        ),
        migrations.AddField(
            model_name='reglaspoliza',
            name='horas_gracia',
            field=models.IntegerField(blank=True, default=0, help_text='Horas adicionales de gracia', null=True),
        ),
        migrations.AddField(
            model_name='reglaspoliza',
            name='horas_vigencia',
            field=models.IntegerField(blank=True, default=0, help_text='Horas adicionales de vigencia', null=True),
        ),
        migrations.AddField(
            model_name='reglaspoliza',
            name='minutos_gracia',
            field=models.IntegerField(blank=True, default=0, help_text='Minutos adicionales de gracia', null=True),
        ),
        migrations.AddField(
            model_name='reglaspoliza',
            name='minutos_vigencia',
            field=models.IntegerField(blank=True, default=0, help_text='Minutos adicionales de vigencia', null=True),
        ),
        migrations.AlterField(
            model_name='reglaspoliza',
            name='dias_gracia',
            field=models.IntegerField(blank=True, default=30, help_text='Días de gracia antes del vencimiento', null=True),
        ),
        migrations.AlterField(
            model_name='reglaspoliza',
            name='dias_vigencia',
            field=models.IntegerField(blank=True, help_text='Días de vigencia de la póliza', null=True),
        ),
        migrations.RemoveField(
            model_name='poliza',
            name='estudiante',
        ),
    ]
