# Generated by Django 6.0 on 2026-01-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_poliza_core_poliza_estudia_99af90_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nombre_beneficiario', models.CharField(max_length=150)),
                ('relacion_beneficiario', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('documento', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('enviado', 'Enviado'), ('descartado', 'Descartado')], default='nuevo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evaluado', models.BooleanField(default=False)),
            ],
        ),
    ]
