# Generated by Django 6.0 on 2026-01-15 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tcasprocesos_tcasdocumentos_tcasactividades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcasdocumentos',
            name='doc_cod_pro',
        ),
        migrations.DeleteModel(
            name='TcasActividades',
        ),
        migrations.DeleteModel(
            name='TcasProcesos',
        ),
    ]
