# Generated by Django 6.0 on 2026-01-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reporteevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteevento',
            name='archivo_documento',
            field=models.FileField(blank=True, null=True, upload_to='reportes/'),
        ),
    ]
