# Generated by Django 6.0 on 2026-01-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_reporteevento_archivo_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteevento',
            name='documento',
        ),
        migrations.AddField(
            model_name='profile',
            name='estado',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
