# Generated by Django 6.0 on 2026-01-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_reporteevento_documento_profile_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='estado',
        ),
    ]
