# Generated by Django 6.0 on 2026-01-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_profile_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='siniestro',
            name='enviado',
            field=models.BooleanField(blank=True, default=False, help_text='Indica si el siniestro fue enviado a la aseguradora', null=True),
        ),
    ]
