# Generated by Django 6.0 on 2026-01-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_factura_beneficiario'),
        ('core', '0013_siniestro_enviado'),
    ]

    operations = [
    ]
