# Generated by Django 6.0 on 2026-01-21 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20260121_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='fechas_limite',
            field=models.JSONField(blank=True, default=list, help_text='Fechas límite para cada documento en formato YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='aseguradora',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aseguradora',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reglaspoliza',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='reglaspoliza',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
