# Generated by Django 6.0 on 2026-01-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_beneficiario_fechas_limite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporteevento',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Reporte de Evento', 'verbose_name_plural': 'Reportes de Eventos'},
        ),
        migrations.AddField(
            model_name='reporteevento',
            name='cedula_estudiante_fallecido',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cédula del estudiante fallecido'),
        ),
        migrations.AddField(
            model_name='reporteevento',
            name='motivo_muerte',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de la muerte'),
        ),
        migrations.AddField(
            model_name='reporteevento',
            name='nombre_estudiante_fallecido',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre completo del estudiante fallecido'),
        ),
        migrations.AlterField(
            model_name='reporteevento',
            name='archivo_documento',
            field=models.FileField(blank=True, help_text='Certificado de defunción (obligatorio)', null=True, upload_to='reportes/'),
        ),
    ]
