# Generated by Django 6.0 on 2026-01-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_reporteevento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siniestro',
            name='cedula_estudiante_fallecido',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cédula del estudiante fallecido'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='motivo_muerte',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de la muerte'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='nombre_estudiante_fallecido',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre completo del estudiante fallecido'),
        ),
    ]
