# Generated by Django 6.0 on 2026-01-29 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_siniestro_cedula_estudiante_fallecido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcasdocumentos',
            name='documento_aseguradora',
            field=models.ForeignKey(blank=True, help_text='Tipo de documento según catálogo de aseguradora', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to='core.documentosaseguradora'),
        ),
    ]
