# Generated by Django 6.0 on 2026-01-29 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_tcasdocumentos_documento_aseguradora'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Impuesto al Valor Agregado', max_digits=10, null=True, verbose_name='IVA (12%)'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='seguro_campesino',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Contribución al SSC', max_digits=10, null=True, verbose_name='Seguro Social Campesino (0.5%)'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='superintendencia',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Contribución a la Superintendencia de Compañías', max_digits=10, null=True, verbose_name='Superintendencia (3.5%)'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='prima_neta',
            field=models.DecimalField(decimal_places=2, help_text='Valor que se paga a la aseguradora (sin impuestos)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Prima Neta'),
        ),
    ]
