# Generated by Django 6.0 on 2026-01-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aseguradora',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RUC'),
        ),
    ]
