# Generated by Django 6.0 on 2026-01-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_aseguradora_ruc'),
    ]

    operations = [
        migrations.AddField(
            model_name='aseguradora',
            name='politicas',
            field=models.TextField(blank=True, null=True, verbose_name='Políticas y Condiciones'),
        ),
    ]
