# Generated by Django 6.0 on 2026-01-07 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_aseguradora_politicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPolitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Políticas 2026 - Versión 1', max_length=200)),
                ('archivo_pdf', models.FileField(upload_to='politicas_pdfs/', verbose_name='Documento PDF')),
                ('terminos_texto', models.TextField(verbose_name='Términos y Condiciones (Texto)')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('fecha_vigencia', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='configuracion.aseguradora')),
            ],
        ),
    ]
