# Generated by Django 6.0 on 2026-01-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_documentopolitica'),
    ]

    operations = [
        migrations.AddField(
            model_name='aseguradora',
            name='dias_maximos_reporte',
            field=models.PositiveIntegerField(default=30, help_text='Límite de días tras el evento para aceptar el reclamo.', verbose_name='Días máximos para reportar'),
        ),
    ]
