# Generated by Django 6.0 on 2026-01-14 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_aseguradora_dias_maximos_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=200, verbose_name='Nombre del Documento (Ej: Acta Defunción)')),
                ('tipo_siniestro', models.CharField(choices=[('accidente', 'Accidente'), ('enfermedad', 'Enfermedad grave'), ('hospitalizacion', 'Hospitalización'), ('fallecimiento', 'Fallecimiento'), ('otro', 'Otro')], max_length=20, verbose_name='Aplica para')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='¿Es obligatorio?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='configuracion.aseguradora')),
            ],
        ),
    ]
