# Generated by Django 6.0 on 2026-01-12 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_asesor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='nombre',
        ),
    ]
