# Generated by Django 6.0 on 2026-01-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_asesor', '0002_remove_beneficiario_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrida', 'Híbrida')], max_length=15)),
                ('nivel', models.CharField(choices=[('grado', 'Grado'), ('posgrado', 'Posgrado')], max_length=15)),
                ('carrera', models.CharField(max_length=100)),
                ('periodo_academico', models.CharField(choices=[('OCT/2025-FEB/2026', 'OCT/2025 - FEB/2026'), ('ABR/2026-AGO/2026', 'ABR/2026 - AGO/2026')], max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('fallecido', 'Fallecido'), ('inactivo', 'Inactivo')], default='activo', max_length=15)),
                ('fecha_defuncion', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
