# Generated by Django 6.0 on 2026-01-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_asesor', '0003_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='tiempo_trancurrido',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
