# Generated by Django 6.0 on 2026-01-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_asesor', '0004_estudiante_tiempo_trancurrido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='tiempo_trancurrido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
