# Generated by Django 6.0 on 2026-01-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_asesor', '0005_alter_estudiante_tiempo_trancurrido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='tiempo_trancurrido',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tiempo_transcurrido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
