# Generated by Django 6.0 on 2026-01-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siniestros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siniestro',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='siniestros/'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='relacion_beneficiario',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
