# Generated by Django 6.0 on 2026-01-03 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siniestros', '0002_siniestro_documento_siniestro_email_contacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=13, unique=True, verbose_name='Cédula')),
                ('codigo_estudiante', models.CharField(max_length=20, unique=True, verbose_name='Código de Estudiante')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('carrera', models.CharField(max_length=150, verbose_name='Carrera')),
                ('nivel', models.CharField(blank=True, max_length=50, verbose_name='Nivel/Semestre')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('egresado', 'Egresado'), ('suspendido', 'Suspendido'), ('graduado', 'Graduado'), ('retirado', 'Retirado')], default='activo', max_length=20, verbose_name='Estado')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.RemoveField(
            model_name='poliza',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='tipo',
            field=models.CharField(blank=True, choices=[('accidente', 'Accidente'), ('enfermedad', 'Enfermedad grave'), ('hospitalizacion', 'Hospitalización'), ('fallecimiento', 'Fallecimiento'), ('otro', 'Otro')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='estudiante',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poliza', to='siniestros.estudiante'),
            preserve_default=False,
        ),
    ]
