# Generated by Django 6.0 on 2026-01-14 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_asesor', '0003_estudiante'),
        ('siniestros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poliza',
            name='usuario',
        ),
        migrations.AddField(
            model_name='poliza',
            name='estudiante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poliza', to='panel_asesor.estudiante'),
        ),
    ]
