# Generated by Django 6.0 on 2026-01-05 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        ('siniestros', '0002_alter_poliza_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='aseguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuracion.aseguradora'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='modalidad',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('DISTANCIA', 'Distancia')], default='PRESENCIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='poliza',
            name='tipo_estudiante',
            field=models.CharField(choices=[('GRADO', 'Grado'), ('POSTGRADO', 'Postgrado')], default='GRADO', max_length=20),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('pagada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='siniestros.poliza')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='siniestros.factura')),
            ],
        ),
    ]
