# Generated by Django 6.0 on 2026-01-05 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siniestros', '0003_poliza_aseguradora_poliza_modalidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='fecha',
            new_name='fecha_emision',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='fecha',
            new_name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='created_at',
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], default='TRANSFERENCIA', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='poliza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='siniestros.poliza'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='siniestros.factura'),
            preserve_default=False,
        ),
    ]
