# Generated by Django 6.0 on 2026-01-14 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siniestros', '0004_rename_fecha_factura_fecha_emision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='evidencias_siniestros/%Y/%m/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='siniestros.siniestro')),
            ],
        ),
    ]
